# This file is used to set the output format of chill commands according to the format expected by VenueServer.
# This format is the same as the system default of Europa and Psyche GDS hosts.
csvQuery.EvrQuery=sessionId,sessionHost,name,module,level,eventId,vcid,dssId,fromSse,realtime,sclk,scet,ert,rct,message,metadataKeywordList,metadataValuesList

csvQuery.ChanvalQuery=sessionId,sessionHost,channelId,dssId,vcid,name,module,ert,scet,sclk,dn,eu,status,dnAlarmState,euAlarmState,realtime,type

csvQuery.ProductQuery=sessionId,sessionHost,vcid,apid,productType,productCreationTime,scet,ert,sclk,fullPath,commandNumber,dvtCoarse,dvtFine,totalParts,seqId,seqVersion,cfdpTransactionId,fileSize,checksum,groundStatus,version
